/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API de Gerenciamento do louvor
 * Organizador das musicas e gerenciamento de escalações do louvor da igreja
 * OpenAPI spec version: v1
 */

export interface LineupMemberSerializers {
  readonly id?: number;
  readonly member_display?: string;
  readonly function_display?: string;
  readonly created_at?: string;
  readonly updated_at?: string;
  /** @maxLength 150 */
  member_name_snapshot?: string;
  /** @maxLength 100 */
  function_name_snapshot?: string;
  lineup: number;
  /** @nullable */
  member: number | null;
  /** @nullable */
  function: number | null;
}
