/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API de Gerenciamento do louvor
 * Organizador das musicas e gerenciamento de escalações do louvor da igreja
 * OpenAPI spec version: v1
 */
import type { UserSerializers } from './userSerializers';
import type { MemberFunctionsSerializers } from './memberFunctionsSerializers';

export interface MemberMe {
  readonly id?: number;
  user?: UserSerializers;
  readonly function?: readonly MemberFunctionsSerializers[];
  readonly profile_picture?: string;
  readonly created_at?: string;
  readonly updated_at?: string;
  /**
   * @minLength 1
   * @maxLength 150
   */
  name: string;
  availability?: boolean;
  /** @maxLength 14 */
  cell_phone?: string;
}
