/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API de Gerenciamento do louvor
 * Organizador das musicas e gerenciamento de escalações do louvor da igreja
 * OpenAPI spec version: v1
 */

export interface MusicCategorySerializers {
  readonly id?: number
  /**
   * @minLength 1
   * @maxLength 50
   */
  category_name: string
}
