/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API de Gerenciamento do louvor
 * Organizador das musicas e gerenciamento de escalações do louvor da igreja
 * OpenAPI spec version: v1
 */
import type { MusicCategorySerializers } from './musicCategorySerializers'
import type { MusicChordSerializers } from './musicChordSerializers'

export interface MusicSerializers {
  readonly id?: number
  /**
   * @minLength 1
   * @maxLength 100
   */
  music_title: string
  /**
   * @minLength 1
   * @maxLength 100
   */
  author: string
  /**
   * @minLength 1
   * @maxLength 10
   */
  music_tone: string
  /** @minLength 1 */
  music_text: string
  /** @maxLength 255 */
  music_link?: string
  readonly category?: readonly MusicCategorySerializers[]
  readonly music_chord?: readonly MusicChordSerializers[]
  readonly created_at?: string
  readonly updated_at?: string
  category_ids?: number[]
  music_chord_ids?: number[]
}
