/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API de Gerenciamento do louvor
 * Organizador das musicas e gerenciamento de escalações do louvor da igreja
 * OpenAPI spec version: v1
 */

export interface PlaylistSerializers {
  readonly id?: number;
  readonly created_at?: string;
  readonly updated_at?: string;
  /** @maxLength 100 */
  playlist_name: string;
  playlist_date?: string;
  music?: number[];
}
