/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API de Gerenciamento do louvor
 * Organizador das musicas e gerenciamento de escalações do louvor da igreja
 * OpenAPI spec version: v1
 */

export interface PraiseLineupSerializers {
  readonly id?: number;
  readonly playlist_display?: string;
  readonly playlist_link_display?: string;
  readonly created_at?: string;
  readonly updated_at?: string;
  lineup_date?: string;
  /** @maxLength 100 */
  lineup_event?: string;
  /** @nullable */
  playlist?: number | null;
}
