/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API de Gerenciamento do louvor
 * Organizador das musicas e gerenciamento de escalações do louvor da igreja
 * OpenAPI spec version: v1
 */

export type PraiseVerifyRegistrationTokenListParams = {
  /**
   * Token de verificação recebido por e-mail
   */
  token: string
}
