/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API de Gerenciamento do louvor
 * Organizador das musicas e gerenciamento de escalações do louvor da igreja
 * OpenAPI spec version: v1
 */

export type PraiseScaleHistoryList200ScalesItem = {
  id?: number;
  lineup_date?: string;
  lineup_event?: string;
  function_name?: string;
};
