/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API de Gerenciamento do louvor
 * Organizador das musicas e gerenciamento de escalações do louvor da igreja
 * OpenAPI spec version: v1
 */
import type { PraiseMusicMostPlayedList200TopMusicsItem } from './praiseMusicMostPlayedList200TopMusicsItem';

export type PraiseMusicMostPlayedList200 = {
  top_musics?: PraiseMusicMostPlayedList200TopMusicsItem[];
};
