/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API de Gerenciamento do louvor
 * Organizador das musicas e gerenciamento de escalações do louvor da igreja
 * OpenAPI spec version: v1
 */
import type { PraiseMemberMostEscalatedList200TopMembersItem } from './praiseMemberMostEscalatedList200TopMembersItem';

export type PraiseMemberMostEscalatedList200 = {
  top_members?: PraiseMemberMostEscalatedList200TopMembersItem[];
};
