/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API de Gerenciamento do louvor
 * Organizador das musicas e gerenciamento de escalações do louvor da igreja
 * OpenAPI spec version: v1
 */

export type PraisePraiseLineupGetPlaylists200ScalesItem = {
  id?: number;
  lineup_event?: string;
  lineup_date?: string;
  playlist?: number;
  playlist_display?: string;
  playlist_link_display?: string[];
};
