/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API de Gerenciamento do louvor
 * Organizador das musicas e gerenciamento de escalações do louvor da igreja
 * OpenAPI spec version: v1
 */
import type { PraiseScaleHistoryList200ScalesItem } from './praiseScaleHistoryList200ScalesItem';

export type PraiseScaleHistoryList200 = {
  scales?: PraiseScaleHistoryList200ScalesItem[];
};
