/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API de Gerenciamento do louvor
 * Organizador das musicas e gerenciamento de escalações do louvor da igreja
 * OpenAPI spec version: v1
 */
import type { PraisePraiseLineupGetPlaylists200ScalesItem } from './praisePraiseLineupGetPlaylists200ScalesItem';

export type PraisePraiseLineupGetPlaylists200 = {
  scales?: PraisePraiseLineupGetPlaylists200ScalesItem[];
};
