/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API de Gerenciamento do louvor
 * Organizador das musicas e gerenciamento de escalações do louvor da igreja
 * OpenAPI spec version: v1
 */

export type PraiseMusicUploadPdf200 = {
  /** HTML formatado com as cifras extraídas do PDF, dentro de uma tag <pre>. */
  html?: string;
  /** Todas as cifras presentes no texto. */
  chords?: string[];
};
