/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API de Gerenciamento do louvor
 * Organizador das musicas e gerenciamento de escalações do louvor da igreja
 * OpenAPI spec version: v1
 */
import type { PraiseMusicMusics200MusicsItem } from './praiseMusicMusics200MusicsItem';

export type PraiseMusicMusics200 = {
  counts?: number;
  musics?: PraiseMusicMusics200MusicsItem[];
};
