/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API de Gerenciamento do louvor
 * Organizador das musicas e gerenciamento de escalações do louvor da igreja
 * OpenAPI spec version: v1
 */

export type PraiseSlidesGeneratorCreateBody = {
  /** ID da playlist cujas músicas serão usadas para gerar os slides */
  playlist_id: number;
};
