/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API de Gerenciamento do louvor
 * Organizador das musicas e gerenciamento de escalações do louvor da igreja
 * OpenAPI spec version: v1
 */

export interface RegisterUser {
  /** @minLength 1 */
  first_name: string;
  /** @minLength 1 */
  last_name: string;
  /** @minLength 1 */
  username: string;
  /** @minLength 1 */
  password: string;
  /** @minLength 1 */
  email: string;
  /** @minLength 1 */
  cell_phone: string;
  /**
   * @minLength 1
   * @maxLength 500
   */
  token: string;
}
