/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API de Gerenciamento do louvor
 * Organizador das musicas e gerenciamento de escalações do louvor da igreja
 * OpenAPI spec version: v1
 */
import type { SendEmailResponseFailedItem } from './sendEmailResponseFailedItem';

export interface SendEmailResponse {
  /** E-mails enviados com sucesso. */
  sent: string[];
  /** Lista de e-mails que falharam com detalhes do erro. */
  failed: SendEmailResponseFailedItem[];
}
