/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API de Gerenciamento do louvor
 * Organizador das musicas e gerenciamento de escalações do louvor da igreja
 * OpenAPI spec version: v1
 */

export interface TokenRefresh {
  /** @minLength 1 */
  refresh: string
  /** @minLength 1 */
  readonly access?: string
}
