/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API de Gerenciamento do louvor
 * Organizador das musicas e gerenciamento de escalações do louvor da igreja
 * OpenAPI spec version: v1
 */

export interface TokenVerification {
  /** Indica se o token é válido. */
  valid: boolean
  /**
   * Email associado ao token válido.
   * @minLength 1
   */
  email?: string
  /**
   * Mensagem de erro, caso o token seja inválido.
   * @minLength 1
   */
  detail?: string
}
