/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API de Gerenciamento do louvor
 * Organizador das musicas e gerenciamento de escalações do louvor da igreja
 * OpenAPI spec version: v1
 */

export interface UserSerializers {
  readonly id?: number
  /**
   * @minLength 1
   * @maxLength 128
   */
  password: string
  /**
   * Obrigatório. 150 caracteres ou menos. Letras, números e @/./+/-/_ apenas.
   * @minLength 1
   * @maxLength 150
   * @pattern ^[\w.@+-]+$
   */
  username: string
  /** @maxLength 150 */
  first_name?: string
  /** @maxLength 150 */
  last_name?: string
  /** @maxLength 254 */
  email?: string
}
